#!/usr/bin/env bash

if [ "$1" != "" ]; then
  unzip -o -j "$1" -d "./tmp"
  xmllint --format "./tmp/document.xml" > "./tmp/document-pretty.xml"
  # xmllint --format "./tmp/document2.xml" > "./tmp/document2-pretty.xml"
fi

xmllint -noout -nonet \
  -schema "./schemas/microsoft/wml-2010.xsd" \
  "./tmp/document-pretty.xml" 2>&1

