#!/usr/bin/env bash

if [ "$1" != "" ]; then
  rm -rf tmp
  unzip -j -o "$1" "word/*.xml" -d "./tmp"
  for i in ./tmp/*.xml; do
    xmllint --format "${i}" > "${i}.pretty.xml"
  done
fi

XSD="schemas/microsoft/wml-2010.xsd"

failed=0
for i in ./tmp/*.pretty.xml; do
  xmllint -noout -nonet \
    -schema "${XSD}" \
    "${i}" 2>&1 || failed=1
done
exit "${failed}"
